# Generated by Django 5.2.4 on 2025-10-22 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='external_id',
        ),
    ]
